env:
  - CGO_ENABLED=0
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    binary: tflint-ruleset-aws-serverless
archives:
  - id: zip
    name_template: "tflint-ruleset-aws-serverless_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*
changelog:
  skip: true
checksum:
  name_template: "checksums.txt"
release:
  github:
    owner: awslabs
    name: serverless-rules
  name_template: "Version {{ .Version }}"